{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 3\n  -4\n  +3", "trace": "self = <test_case_pytest.test_main.Test_main object at 0x0000006799CBE4E0>\n\n    def test_b(self):\n        # try:\n        B = comd.jian()\n>       assert 4 == B\nE       assert 4 == 3\nE         -4\nE         +3\n\ntest_case_pytest\\test_main.py:21: AssertionError"}, "attachments": [{"name": "log", "source": "7cf1252f-8b06-4e40-8e2c-30a1dc0b8bee-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "4a6c8f87-9b12-4913-b2d6-85cd98ce00e5-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "28ea9542-8293-4fff-b742-4c92a910be83-attachment.txt", "type": "text/plain"}], "start": 1548681430708, "stop": 1548681430710, "uuid": "1d217dcc-6433-4149-a5e5-b8c4dfcf8023", "historyId": "2a7aea8402509f29d9693222889dc530", "fullName": "test_case_pytest.test_main.Test_main#test_b", "labels": [{"name": "parentSuite", "value": "test_case_pytest"}, {"name": "suite", "value": "test_main"}, {"name": "subSuite", "value": "Test_main"}, {"name": "host", "value": "admin"}, {"name": "thread", "value": "9028-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_pytest.test_main"}]}