{"name": "test_b", "status": "failed", "statusDetails": {"message": "AssertionError: assert 4 == 3\n  -4\n  +3", "trace": "self = <test_case_pytest.test_main.Test_main object at 0x000000EB29C391D0>\n\n    def test_b(self):\n        # try:\n        B = comd.jian()\n>       assert 4 == B\nE       assert 4 == 3\nE         -4\nE         +3\n\ntest_case_pytest\\test_main.py:21: AssertionError"}, "attachments": [{"name": "log", "source": "de846bcf-1e23-44f3-ba42-df35ead4c270-attachment.txt", "type": "text/plain"}, {"name": "stdout", "source": "1c2fd429-8cc0-4b22-95ea-66c34ba0fa6c-attachment.txt", "type": "text/plain"}, {"name": "stderr", "source": "5dfe457a-61b2-46db-b127-416c844e93f3-attachment.txt", "type": "text/plain"}], "start": 1548681293471, "stop": 1548681293473, "uuid": "abb3e762-ff0d-4a70-9956-d35aaf211438", "historyId": "2a7aea8402509f29d9693222889dc530", "fullName": "test_case_pytest.test_main.Test_main#test_b", "labels": [{"name": "parentSuite", "value": "test_case_pytest"}, {"name": "suite", "value": "test_main"}, {"name": "subSuite", "value": "Test_main"}, {"name": "host", "value": "admin"}, {"name": "thread", "value": "4016-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_case_pytest.test_main"}]}